---
- name: My task
  hosts: all
  tasks:
    - name: Setting gpg-key
      shell: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
       

    - name: Installing gh tool
      become: Yes
      apt:
        pkg:
          - gh
        state: latest
        update_cache: false
      ignore_errors: yes


